### ISSUE TITLE
Problem with External Project

### ISSUE THREAD

**Issue by Mike-E-angelo** [cureos/shim#10]
Hello,

First off... your project works like a champ!  I just had to install it and I was able to implement the [Serializable] attribute on a PCL class.  No fuss.  AMAZING.  Thank you. :)

However, I did run into a problem with another really amazing project once I installed this one and had to remove it.  We were wondering if you can maybe take a look at it and help us out. :)

Here's the issue:
https://github.com/kzu/SmartReferences/issues/1

Thanks again... donation is on the way! (This needs to be a built-in feature to GitHub!!!)

**Comment by Mike-E-angelo** [comment]
(For reference, here is the implementation of your product in mine:
https://github.com/DragonSpark/Framework/blob/Multiversal/Prism/Source/Prism/Modularity/ModuleInfo.cs#L12)

**Comment by anders9ustafsson** [comment]
Hi @Michael-DST and thanks for reporting this issue!

I need to give this some thought. I am not sure I understand exactly what _SmartReferences_ does and how it affects/is affected by _Shim_, so I have to figure that out first. Maybe you could dwell a little on what you are trying to achieve, especially how _SmartReferences_ is intended to work for you.

I'll get back to you as soon as I have a few more answers.

Best regards,
Anders

**Comment by Mike-E-angelo** [comment]
OK... don't think too hard @anders9ustafsson.  I believe this problem can be solved on SmartReferences side with an ignore file of some sort.  I hope to have a PR soon around this there to do just that.  I am closing this issue for now and will ping back here if needed.  Thanks again!

**Comment by anders9ustafsson** [comment]
Hi again, I just looked at it, and if I understand how _SmartReferences_ work, I think I understand the problem.

You get the compilation error in a .NET project, right, which is referencing a PCL project? And _SmartReferences_ try to pick the _Shim_ DLL from your PCL project since _Shim_ is not explicitly referenced in your .NET project?

That's the problem, then. The PCL version of the _Shim_ library is only intended to work together with other PCL libraries. If you from an end-user application for whatever platform are referencing a PCL project which consumes _Shim_, you must explicitly reference _Shim_ in your end-user application as well. NuGet does the _magic_ and picks the DLL for the correct platform. But for things to work _Shim_ must be referenced in the end-user application also.

I realize that I need to be clearer on this in the _Shim_ documentation. I'll try and write up a wiki page on the subject as soon as possible.

Thanks for spotting this! Good to know the caveats :-)

Best regards,
Anders

**Comment by Mike-E-angelo** [comment]
Cooooooool... yep, I just got the PR in... now there's an IgnoreAssemblies.txt file that can be used to ignore assemblies... so users of Shim can just add "Shim" to it and it will work as before.  So we are goooooood!  Thanks again. :)

**Comment by anders9ustafsson** [comment]
@Michael-DST I have added an [overview](https://github.com/cureos/shim/wiki/Overview) on the Shim wiki. Hopefully it should explain a little better why you have run in to these problems.

**Comment by Mike-E-angelo** [comment]
Most excellent!  This is really cool and a clever technique.  I completely understand how it works now.  Obviously, you do not want to have platform-specific code in your PCL, but in the case that you do, this is how to get around it.

The [Serializable] is just such poor design.  You would think at the least the PCL profiles would have that in there to support legacy scenarios.  OR they would _at the very least_ update .NET framework to just allow [Serializable] at the root class.  Seems pretty ridiculous to require it for the entire chain, especially when that chain could be out of the control of the author's domain.  Anyways, I digress.  Problem solved... for now. :P
