### ISSUE TITLE
Add support for PCL Profile 136

### ISSUE THREAD

**Issue by nowol** [cureos/shim#33]
Hello,

Would it be possible for you to support Profile136?  I think that it should be relatively painless to support it since you already have Profile328. 

On a related note, I tried adding a reference to the Shim package in a project that targets Profile328 and I was not able to:

```
Could not install package 'shim 1.0.2.50909'. You are trying to install this package into a project that targets 'portable-net40+sl50+win+wpa81+wp80', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

It looks like the Nuget package is missing the folder for Profile328.

**Comment by anders9ustafsson** [comment]
@nowol I don't have the Profile 136 targets in my head right now, but if I remember correctly the 136 targets are a pure sub-set of Profile 328, right? Then I don't see the need to support Profile 136, because when you use your own PCL library in an application for a specific target, you will need to reference the _Shim_ library for that specific target as well. (And you don't need to worry about selecting the right _Shim_ instance for your application target, _NuGet_ does that for you automatically as long as you explicitly reference _Shim_ in your application.)

**Comment by nowol** [comment]
It looks like you're right according to this page: http://embed.plnkr.co/03ck2dCtnJogBKHJ9EjY
Do you have a problem with leaving this issue open until I can test it with your next release?

**Comment by anders9ustafsson** [comment]
@nowol No worries, I'll leave the issue open for now :-)

**Comment by orck-adrouin** [comment]
I tested the new alpha version and it works with a Profile 136.
You can close this issue.

Thanks!

**Comment by nowol** [comment]
I tested the new alpha version and it works with a Profile 136.

Thanks!
