### ISSUE TITLE
No support for Universal Windows Platform

### ISSUE THREAD

**Issue by godrose** [cureos/shim#49]
Getting the message "shim 2.0.0 is not compatible with UAP,Version=v10.0 (win10-x86)", etc.
Any plans to support this platform?

**Comment by anders9ustafsson** [comment]
@godrose Hmm, strange that it is not working for you? I'll check and get back to you as soon as possible.

**Comment by godrose** [comment]
Actually didn't try that but does 2.0.0 version support the latest Xamarin.Forms?

**Comment by anders9ustafsson** [comment]
@godrose I haven't tried it, but I see no reason why it shouldn't. 

An hour ago I wrote a lengthy comment about my recent findings, but apparently I didn't press the _Comment_ button? Can't see this comment anywhere?

Anyway, I am able to download _Shim_ from NuGet for a UWP application. UWP references the PCL Profile 32 (Windows 8.1 + Windows Phone 8.1) instance. Not sure why downloading from NuGet does not work for you.

Now, even if the NuGet download works fine (for me), it does turn out that the Profile 32 _Shim_ instance **is** nevertheless incompatible with UWP, since the assembly implements a number of types and methods that are simultaneously defined in the UWP reference assemblies. For example, `System.IO.File`.

So it **is** necessary to add a UWP specific _Shim_ instance to the NuGet package after all, and urgently. I'll start dealing with this as soon as possible.

Many thanks for initiating this investigation.

**Comment by godrose** [comment]
Any expectations for the release date?

**Comment by anders9ustafsson** [comment]
@godrose No, I can't give any date for this. If it is business critical for you, you should be able to fork the repository and add a separate UWP library yourself, similar to the Win 8.1+WPA 8.1 library but modified to build for UWP. (If you manage to do this successfully, it is of course appreciated if you share your enhancements.) Or you can make a business proposition to "info at cureos dot com" and I will be able to prioritize this work.

Regards,
Anders

**Comment by godrose** [comment]
If i manage to do so when will you be able to release a new package? it doesn't have to be 2.1. I think 2.0.1 will do for this bugfix.

**Comment by anders9ustafsson** [comment]
@godrose Provided the pull request can be accepted without too many changes, I can publish a new NuGet package more or less right away. It will be a bug-fix release 2.0.1.

**Comment by anders9ustafsson** [comment]
@godrose Work is ongoing, I hope to be able to make a pre-release later tonight.

**Comment by anders9ustafsson** [comment]
NuGet pre-release 2.1.0-pre published, with UWP support. Please try it out and see if it works for your UWP application, @godrose .

**Comment by godrose** [comment]
Cool.I will try it out.Thanks a bunch!

**Comment by godrose** [comment]
@anders9ustafsson  It works!
Thanks for the effort!
