### ISSUE TITLE
Bitmap defined multiple times when referencing System.Drawing

### ISSUE THREAD

**Issue by thiagojedi** [cureos/shim#56]
Hi.

I'm trying to use "Aforge portable" with the (.net wrapper for) Tesseract-OCR, on Mono/Linux but when I build the project two things happens:

1- When not referencing System.Drawing, the Tesseract code raises a error saying something like "We need the Bitmap in System.Drawing.dll"

2- When referencing System.Drawing, whenever I use System.Drawing.Bitmap there's a error saying "Bitmap is defined multiple times".

At issue #23 there's a answer telling that Shim.Drawing should not be used as replacement for System.Drawing, which makes sense. But since they're using the same namespace, I can't separate the two of them.

My question is: Is there a way to use both Bitmaps in the same project?

**Comment by anders9ustafsson** [comment]
@thiagoabreu As far as I know, there is no easy way to incorporate both *Shim.Drawing*  and *System.Drawing*  assemblies in the same project.

But since you are running on Mono, I would rather recommend that you skip *Portable AForge* altogether, and instead use the regular *AForge.NET Framework* from [here](https://github.com/andrewkirillov/AForge.NET). You should be able to build it on Mono without problems.

**Comment by thiagojedi** [comment]
Thank you for your reply.

Yeah. That's the thing. The only reason I was testing *Portable AForge* was because AForge.Imaging isn't fully functional on Mono, i.e. applying filters to image throws a "ntdll.dll" error which normally occours when referencing a Win32 dll.

Anyway, I'll try to figure it out some way. Thank you again.
